### ISSUE TITLE
Clase - Stock

### ISSUE THREAD

**Issue by mzkrantz** [nicopetcoff/Gimnasio#19]
- Tenemos que ver si existe stock suficiente para anotar alumnos (no inscribir mas alumnos si no hay stock)
- Tener en cuenta que no podemos asignar y descontar el stock fuera de horario de clase, pero debemos mostrar si hay disponibilidad de acuerdo al punto anterior

**Comment by gordojm** [comment]
#29

**Comment by nicopetcoff** [comment]
resuelto
